# Generated by Django 5.2.9 on 2026-03-19 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="tenant",
            new_name="tenants_ten_slug_63daca_idx",
            old_name="tenants_tenant_slug_idx",
        ),
        migrations.RenameIndex(
            model_name="tenant",
            new_name="tenants_ten_primary_0a67a4_idx",
            old_name="tenants_tenant_primary_domain_idx",
        ),
        migrations.RenameIndex(
            model_name="tenant",
            new_name="tenants_ten_is_acti_8f654a_idx",
            old_name="tenants_tenant_is_active_idx",
        ),
        migrations.RenameIndex(
            model_name="tenantdomain",
            new_name="tenants_ten_tenant__608df7_idx",
            old_name="tenants_domain_tenant_domain_idx",
        ),
        migrations.RenameIndex(
            model_name="tenantdomain",
            new_name="tenants_ten_is_veri_4e0560_idx",
            old_name="tenants_domain_is_verified_idx",
        ),
    ]
