# Generated by Django 5.2.9 on 2026-03-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0002_rename_tenants_tenant_slug_idx_tenants_ten_slug_63daca_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="brand_logo_url",
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name="tenant",
            name="brand_primary_color",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="tenant",
            name="brand_text_color",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
