# Generated by Django 5.2.9 on 2026-03-19 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("drive", "0002_global_short_code"),
        ("drive", "0002_remove_link_uniq_tenant_short_code_and_more"),
    ]

    operations = []
