# Generated by Django 5.2.9 on 2026-03-19 17:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("drive", "0001_initial"),
        (
            "tenants",
            "0002_rename_tenants_tenant_slug_idx_tenants_ten_slug_63daca_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ClickEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("referer", models.URLField(blank=True, max_length=2000)),
                ("country", models.CharField(blank=True, max_length=128)),
                ("region", models.CharField(blank=True, max_length=128)),
                ("city", models.CharField(blank=True, max_length=128)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="click_events",
                        to="drive.link",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="click_events",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tenant", "created_at"],
                        name="analytics_c_tenant__9cba4c_idx",
                    ),
                    models.Index(
                        fields=["link", "created_at"],
                        name="analytics_c_link_id_3b49a2_idx",
                    ),
                ],
            },
        ),
    ]
